### ISSUE TITLE
App kicking my friends out even when whitelisted after latest GTAO update

### ISSUE THREAD

**Issue by Peshmerga1990** [CodeSwine/GTA5Online-Private_Public_Lobby#27] opened 2021-03-20 17:31 UTC
Since the recent GTAO update came out where they sped up the speed for going into GTA Online, the app doesn't keep my friends in lobby anymore, it kicks everyone out even those who are whitelisted, can you please check the issue and release an update ?

**Comment by alcore250** [comment] 2021-03-21 23:56
I am having the same thing happing to me I hope they came with a update I though it my problem.

**Comment by Peshmerga1990** [comment] 2021-03-22 03:37
Nahh buddy, it's not just you, everyone who's using the app have the same problem, some stuff needs to be changed in the app in order to bypass the new GTA Online protocols.

**Comment by alcore250** [comment] 2021-03-22 04:51
one my friends who uses this programe it stilled worked for him

**Comment by Peshmerga1990** [comment] 2021-03-22 09:12
If it's still working for him, what version of the app is he using ? and what version of GTA ? Did he do anything with his PC settings ?

**Comment by alcore250** [comment] 2021-03-22 23:24
i dont know really. he didnt say and i will ask tho

**Comment by Peshmerga1990** [comment] 2021-03-22 23:50
Great, thank you

**Comment by Carsonred** [comment] 2021-04-02 19:22
I'm having the same issue. I've been troubleshooting this for hours. God I wish I saw this forum sooner. Hopefully we can get an update soon.

**Comment by alcore250** [comment] 2021-04-02 21:18
idk if it will be fixed but i hope it gets fixed

**Comment by Peshmerga1990** [comment] 2021-04-03 00:56
i'm checking every day, and still no update sadly 😞

**Comment by alcore250** [comment] 2021-04-03 02:01
yea same i am sad :(

**Comment by CommandoCat** [comment] 2021-04-15 06:36
I hope @CodeSwine updates it soon! =(

**Comment by alcore250** [comment] 2021-04-15 13:42
same here

**Comment by Tmp341** [comment] 2021-04-29 09:05
With [1.53 update](https://support.rockstargames.com/articles/360061161574/GTAV-Title-Update-1-53-Notes-PS4-Xbox-One-PC), Rockstar made some changes on **network connectivity**. After that, some apps like this one started not completely working as intended.

**Comment by Elec0** [comment] 2021-05-17 17:35
Discussion is in https://github.com/CodeSwine/GTA5Online-Private_Public_Lobby/issues/30

**Closed by Elec0** 2021-05-17 17:35 UTC
